CREATE TABLE TBL_USER
(
    ID         CHAR(36) PRIMARY KEY NOT NULL,
    USERNAME   VARCHAR(50)          NOT NULL,
    EMAIL      VARCHAR(100)         NOT NULL,
    PASS       VARCHAR(200)         NOT NULL,
    CREATED_AT TIMESTAMP            NOT NULL
);

CREATE TABLE TBL_MESSAGE
(

    ID           INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FK_USER_FROM CHAR(36) NOT NULL,
    FK_USER_TO   CHAR(36) NOT NULL,
    MESSAGE      TEXT     NOT NULL,
    CREATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,


    CONSTRAINT FK_MESSAGE_USER_FROM
        FOREIGN KEY (FK_USER_FROM) REFERENCES TBL_USER (ID) ON UPDATE CASCADE,

    CONSTRAINT FK_MESSAGE_USER_TO
        FOREIGN KEY (FK_USER_TO) REFERENCES TBL_USER (ID) ON UPDATE CASCADE

);